### ISSUE TITLE
warcraftlogs webhook

### ISSUE THREAD

**Issue by flow0284** [WoWAnalyzer/DiscordBot#11]
Hey, we are using the warcraftlogs webhook. It looks like that your bot dont like this webhook, because he wont respond... Is it possible for you to add support for this webhook so your bot can respond?

**Comment by MartijnHols** [comment]
Thanks for the issue. I just pushed a patch in aa2b2588bebffbd227aa9dcee14ec8cc03ab4e38 that will enable responding to bots. It will take about 5 minutes before it's active.

This was initially disabled to avoid bots spamming each other, but now that we ignore the same link for 1 hour this should not be an issue.

**Comment by flow0284** [comment]
Your update doesn't work. the bot did not respont to warcraftlogs webhook (no bot on server!)
