### ISSUE TITLE
respond to warcraftlogs webhook

### ISSUE THREAD

**Issue by flow0284** [WoWAnalyzer/DiscordBot#12]
> Update to https://github.com/WoWAnalyzer/DiscordBot/issues/11

Your update doesn't work. the bot did not respont to warcraftlogs webhook (no bot on server!)

**Comment by Ashalaya** [comment]
Hey ya, I was wondering if I need to setup something to let your bot interact with the WCL webhook. I have the WoWAnalyzer bot on my discord and setup the webhook for my guild reports. Thx in advance.

**Comment by MartijnHols** [comment]
Hey thanks for getting back about this. I just implemented a fix that should make it work properly with the Warcraft Logs webhook in particular.

**Comment by flow0284** [comment]
Nice thank you. Now its working 👍
